# Simple workflow for deploying static content to GitHub Pages
name: Deploy to Pages

on:
  push:
    branches:
      - devel
  release:
    types: [published]
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch:
          - main
          - devel
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
          fetch-depth: 0
      - run: npm install
      - run: npm list
      - run: npm list --all
      - run: npm run build
      - run: npm run typecheck
      - run: npm run lint
      - run: |
          mkdir ./dist/"${{ matrix.branch }}"
          mv ./package-lock.json ./dist/mbs.js ./dist/mbs.js.map ./dist/"${{ matrix.branch }}"/
      - uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.branch }}
          path: ./dist

  deploy:
    needs: [build]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/checkout@v4
        name: Download previous release artifacts
        with:
          repository: bananarama92/MBS-Artifacts
          path: MBS-Artifacts
          token: ${{ secrets.MBS_ARTIFACTS_TOKEN }}
      - uses: actions/download-artifact@v4
        with:
          path: MBS-Artifacts/artifacts
      - name: Push new release artifacts to the MBS release archive
        if: github.event_name == 'release'
        run: |
          MBS_HASH=$(git rev-parse HEAD)

          cd MBS-Artifacts
          mkdir artifacts/${{ github.event.release.tag_name }}
          cp artifacts/main/package-lock.json artifacts/main/mbs.js artifacts/main/mbs.js.map artifacts/${{ github.event.release.tag_name }}/

          git add artifacts/${{ github.event.release.tag_name }}/*
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "MAINT: Add MBS ${{ github.event.release.tag_name }} release artifacts" -m "Last commit: https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          git push
      - name: Define the latest MBS release
        run: |
          TAG=$(git describe --abbrev=0 --tags)
          echo "New tag: $TAG"
          rm -rf MBS-Artifacts/artifacts/main
          cp -r MBS-Artifacts/artifacts/"$TAG" MBS-Artifacts/artifacts/main
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './MBS-Artifacts/artifacts'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
      - name: Attach release artifacts to GitHub release
        if: github.event_name == 'release'
        uses: AButler/upload-release-assets@v3.0
        with:
          files: 'MBS-Artifacts/artifacts/${{ github.ref_name }}/*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
